// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    return $('div').click(function() {
      if (!($(this).attr('class'))) {
        if ($(this).css('border-color').replace(/\s+/g, '') === 'rgb(255,0,0)') {
          return $(this).css("border-color", "orange");
        } else if ($(this).css('border-color').replace(/\s+/g, '') === 'rgb(255,165,0)') {
          return $(this).css("border-color", "green");
        } else {
          return $(this).css("border-color", "red");
        }
      }
    });
  });

}).call(this);
